Metadata:
  # The name will also show up as the main folder for simulation
  name: KraussCalibration

Blocks:
  CFModelParameters:
    model: "Krauss"
    parameters:
      tau:
        val: ???
        search_space: "uniform"
        args:
          - 0.5
          - 5
      accel:
        val: ???
        search_space: "uniform"
        args:
          - 0.1
          - 7
      decel:
        val: ???
        search_space: "uniform"
        args:
          - 0.1
          - 7

      speedFactor:
        val: ???
        search_space: "uniform"
        args:
          - 0.8
          - 1.8

      actionStepLength:
        val: ???
        search_space: "choice"
        args: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]

      # minGap:
      #   val: ???
      #   search_space: "uniform"
      #   args:
      #     - 0.5
      #     - 20

      sigma:
        val: ???
        search_space: "uniform"
        args:
          - 0.1
          - 1

      sigmaStep:
        val: ???
        search_space: "uniform"
        args:
          - 0.1
          - 1
