Metadata:
  # The name will also show up as the main folder for simulation
  author: mcschrader@crimson.ua.edu
  output: ${oc.env:PROJECT_ROOT}/tmp/${Metadata.name}/${datetime.now:%m.%d.%Y_%H.%M.%S}
  cwd: ${.output}/${.run_id}
  run_id: ???
  simulation_root: ${oc.env:PROJECT_ROOT}/sumo-xml
  random_seed: 7788

Blocks:
  TrajectoryGenerator:
    pair_file: "${oc.env:DATA_PATH}/leaders.parquet"
    max_queue_size: 64
    leader_id: ???
    follower_id: ???

  TrajectoryProcessing:
    generate_function: external.functions.trajectory_loaders.read_trajectories.database_loader
    kwargs:
      traj_file: "${oc.env:DATA_PATH}/processed_followers.parquet"
      # all_leaders_file: "${oc.env:DATA_PATH}/candidate_leaders.parquet"
      follower_id: ${Blocks.TrajectoryGenerator.follower_id}
      leader_id: ${Blocks.TrajectoryGenerator.leader_id}
      step_length: ${Blocks.SimulationConfig.step_length}
      # multi_leader: False

  SimulationConfig:
    start_time: 0
    end_time: 10_000
    net_file: ${Metadata.simulation_root}/net.net.xml
    gui: True
    route_files:
      - ${Metadata.simulation_root}/route.rou.xml
    step_length: 1
    additional_files: null
    additional_sim_params:
      - --seed
      - ${Metadata.random_seed}
      - --start
      - "--step-method.ballistic"
    target_lane: E2_0
    route_name: r_0
    # simulation_output: ${Metadata.cwd}/sumo_output.txt

  CFOptimizeConfig:
    optimization_algo: "NGOpt"
    budget: 2000
    simulation_config: ${Blocks.SimulationConfig}
    early_stopping: True
    early_stopping_tolerance: 100
    seed: ${Metadata.random_seed}

  Error:
    # method: "spacing"
    # error_func: "nrmse_s_v_a"
    # val: "${.nrmse_s_v_a}"
    # include_accel: 
    method: "spacing"
    error_func: "nrmse_s_v"
    val: "${.nrmse_s_v}"
    include_accel: True

Pipeline:
  executor: ray
  parallel_proc: auto
  pipeline:
    - block: CalibrationPipeline
      parallel: True
      # queue_based: False
      number_of_workers: 64
      producers:
        - function: external.functions.sumo_pipelines_adapter.loader_adapter.trajectory_pair_generator
          config: ${Blocks.TrajectoryGenerator}
      consumers:
        - function: external.functions.sumo_pipelines_adapter.optimizer.optimize
          config: ${Blocks.CFOptimizeConfig}
      result_handler:
        function: external.functions.sumo_pipelines_adapter.optimizer.dump_results
        config: {}
